# Generated by Django 4.0.4 on 2022-06-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.TextField(help_text='Descripcion de la pelicula', max_length=100)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='director',
            name='movies',
            field=models.ManyToManyField(to='catalogo.pelicula'),
        ),
    ]
