# Generated by Django 4.0.4 on 2022-06-02 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_pelicula_director_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='movies',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.director'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='tittle',
            field=models.CharField(help_text='Descripcion de la pelicula', max_length=64),
        ),
    ]
